language: c
sudo: required

os:
    - linux

addons:
    apt:
        update: true
        config:
            retries: true
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - gcc-8
            - apache2
            - apache2-dev
            - apache2-ssl-dev
            - libssl1.1
            - libssl-dev
            - libnghttp2-14
            - libnghttp2-dev
            - libcurl4
            - libcurl4-openssl-dev
            - libjansson4
            - libjansson-dev

matrix:
    include:
        - os: linux
          dist: disco
          compiler: gcc
          env:
            - MY_ENV="BASE_OS=ubuntu-disco-gcc-8"
          before_install:
            - sudo apt-get install -y apache2 apache2-dev apache2-ssl-dev libssl1.1
                libssl-dev libnghttp2-14 libnghttp2-dev libcurl4 libcurl4-openssl-dev
                libjansson4 libjansson-dev



before_install:
    - eval "${MY_ENV}"

before_script: 
    - ./buildconf


script: 
    - |
        ./configure && make clean && make && make install


branches:
    only:
        - master

#services:
# - docker
#
#script:
#  - docker build . -t icing/mod_md

