language: c
sudo: required

matrix:
    include:
        - os: linux
          compiler: gcc
          dist: disco
          addons:
              apt:
                  sources:
                      - ubuntu-toolchain-r-test
                  packages:
                      - gcc-8
                      - apache2
                      - apache2-dev
                      - apache2-ssl-dev
                      - libssl1.1
                      - libssl-dev
                      - libnghttp2-14
                      - libnghttp2-dev
                      - libcurl4
                      - libcurl4-openssl-dev
                      - libjansson4
                      - libjansson-dev
                      - python3
          env:
              - MATRIX_EVAL="BASE_OS=ubuntu-disco-gcc-8"

before_install:
    - eval "${MATRIX_EVAL}"

before_script: ./buildconf

script: |
    dpkg --listfiles apache2 && apxs && 
    ./configure && make clean && make && make install

branches:
    only:
        - master

#services:
# - docker
#
#script:
#  - docker build . -t icing/mod_md

