language: c
sudo: required

addons:
  apt:
    config:
      retries: true
    sources: &common_sources
      - ubuntu-toolchain-r-test
    packages: &common_packages
      - gcc-8
      - apache2
      - apache2-dev
      - apache2-ssl-dev
      - libnghttp2-14
      - libnghttp2-dev
      - libcurl4
      - libcurl4-openssl-dev
      - libjansson4
      - libjansson-dev
      - python3

matrix:
  include
    - os: linux
      compiler: gcc
      dist: cosmic
      addons:
        apt:
          sources:
            - *common_sources
          packages:
            - *common_packages
    - os: linux
      compiler: gcc
      dist: xenial
      addons:
        apt:
          sources:
            - *common_sources
          packages:
            - *common_packages

jobs:
  include:
    - stage: compile
      before_install:
        - ./buildconf
      install: |
        ./configure --with-apxs=/usr/bin/apxs && 
        make clean && make && make install
      script: echo "ok."

stages:
  - compile

branches:
  only:
    - master

#services:
# - docker
#
#script:
#  - docker build . -t icing/mod_md

